# Generated by Django 4.0.6 on 2022-07-13 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insumos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamento', models.CharField(max_length=30)),
                ('laboratorio', models.CharField(max_length=50)),
                ('stock', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=30)),
                ('rut', models.CharField(max_length=30)),
                ('correo', models.CharField(max_length=30)),
                ('hijos', models.CharField(max_length=30)),
                ('nacionalidad', models.IntegerField(choices=[(1, 'Chileno'), (2, 'Venenzolano'), (3, 'Haitiano'), (4, 'Colombiano'), (5, 'Otros')])),
                ('cuidados_especiales', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=30)),
                ('estado_civil', models.IntegerField(choices=[(1, 'Viudo/a'), (2, 'Casado/a'), (3, 'Soltero/a'), (4, 'Divorciado/a')])),
            ],
        ),
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrePaciente', models.CharField(max_length=50)),
                ('rutPaciente', models.CharField(max_length=12)),
                ('correoPaciente', models.CharField(max_length=320)),
                ('hijosPaciente', models.CharField(max_length=2)),
                ('paisPaciente', models.CharField(max_length=30)),
                ('informacionEspecialPaciente', models.CharField(max_length=300)),
                ('telefonoPaciente', models.CharField(max_length=10)),
                ('estadoCivilPaciente', models.CharField(max_length=50)),
            ],
        ),
    ]
