# Generated by Django 4.0.6 on 2022-07-13 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_fundacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aportadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreAportador', models.CharField(max_length=50)),
                ('rutAportador', models.CharField(max_length=12)),
                ('correoAportador', models.CharField(max_length=320)),
                ('peticion', models.CharField(max_length=150)),
                ('pais', models.CharField(max_length=30)),
                ('monto', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Pacientes',
        ),
    ]
